//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.225
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
    // z opcją /str lub rekompiluj projekt Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GridLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GridLocalization() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GridLocalization", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Zastępuje właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add new record.
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel changes.
        /// </summary>
        internal static string CancelChanges {
            get {
                return ResourceManager.GetString("CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to delete this record?.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Displaying items {0} - {1} of {2}.
        /// </summary>
        internal static string DisplayingItems {
            get {
                return ResourceManager.GetString("DisplayingItems", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu And.
        /// </summary>
        internal static string FilterAnd {
            get {
                return ResourceManager.GetString("FilterAnd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu is false.
        /// </summary>
        internal static string FilterBoolIsFalse {
            get {
                return ResourceManager.GetString("FilterBoolIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu is true.
        /// </summary>
        internal static string FilterBoolIsTrue {
            get {
                return ResourceManager.GetString("FilterBoolIsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Clear Filter.
        /// </summary>
        internal static string FilterClear {
            get {
                return ResourceManager.GetString("FilterClear", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is equal to.
        /// </summary>
        internal static string FilterDateEq {
            get {
                return ResourceManager.GetString("FilterDateEq", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is after or equal to.
        /// </summary>
        internal static string FilterDateGe {
            get {
                return ResourceManager.GetString("FilterDateGe", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is after.
        /// </summary>
        internal static string FilterDateGt {
            get {
                return ResourceManager.GetString("FilterDateGt", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is before or equal to.
        /// </summary>
        internal static string FilterDateLe {
            get {
                return ResourceManager.GetString("FilterDateLe", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is before.
        /// </summary>
        internal static string FilterDateLt {
            get {
                return ResourceManager.GetString("FilterDateLt", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is not equal to.
        /// </summary>
        internal static string FilterDateNe {
            get {
                return ResourceManager.GetString("FilterDateNe", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is equal to.
        /// </summary>
        internal static string FilterEnumEq {
            get {
                return ResourceManager.GetString("FilterEnumEq", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is not equal to.
        /// </summary>
        internal static string FilterEnumNe {
            get {
                return ResourceManager.GetString("FilterEnumNe", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is equal to.
        /// </summary>
        internal static string FilterForeignKeyEq {
            get {
                return ResourceManager.GetString("FilterForeignKeyEq", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is not equal to.
        /// </summary>
        internal static string FilterForeignKeyNe {
            get {
                return ResourceManager.GetString("FilterForeignKeyNe", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is equal to.
        /// </summary>
        internal static string FilterNumberEq {
            get {
                return ResourceManager.GetString("FilterNumberEq", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is greater than or equal to.
        /// </summary>
        internal static string FilterNumberGe {
            get {
                return ResourceManager.GetString("FilterNumberGe", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is greater than.
        /// </summary>
        internal static string FilterNumberGt {
            get {
                return ResourceManager.GetString("FilterNumberGt", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is less than or equal to.
        /// </summary>
        internal static string FilterNumberLe {
            get {
                return ResourceManager.GetString("FilterNumberLe", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is less than.
        /// </summary>
        internal static string FilterNumberLt {
            get {
                return ResourceManager.GetString("FilterNumberLt", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is not equal to.
        /// </summary>
        internal static string FilterNumberNe {
            get {
                return ResourceManager.GetString("FilterNumberNe", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Or.
        /// </summary>
        internal static string FilterOr {
            get {
                return ResourceManager.GetString("FilterOr", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu -Select value-.
        /// </summary>
        internal static string FilterSelectValue {
            get {
                return ResourceManager.GetString("FilterSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show rows with value that.
        /// </summary>
        internal static string FilterShowRows {
            get {
                return ResourceManager.GetString("FilterShowRows", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ends with.
        /// </summary>
        internal static string FilterStringEndsWith {
            get {
                return ResourceManager.GetString("FilterStringEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is equal to.
        /// </summary>
        internal static string FilterStringEq {
            get {
                return ResourceManager.GetString("FilterStringEq", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Is not equal to.
        /// </summary>
        internal static string FilterStringNe {
            get {
                return ResourceManager.GetString("FilterStringNe", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Does not contain.
        /// </summary>
        internal static string FilterStringNotSubstringOf {
            get {
                return ResourceManager.GetString("FilterStringNotSubstringOf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Starts with.
        /// </summary>
        internal static string FilterStringStartsWith {
            get {
                return ResourceManager.GetString("FilterStringStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Contains.
        /// </summary>
        internal static string FilterStringSubstringOf {
            get {
                return ResourceManager.GetString("FilterStringSubstringOf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Drag a column header and drop it here to group by that column.
        /// </summary>
        internal static string GroupHint {
            get {
                return ResourceManager.GetString("GroupHint", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No records to display..
        /// </summary>
        internal static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Page .
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu of {0}.
        /// </summary>
        internal static string PageOf {
            get {
                return ResourceManager.GetString("PageOf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu sorted ascending.
        /// </summary>
        internal static string SortedAsc {
            get {
                return ResourceManager.GetString("SortedAsc", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu sorted descending.
        /// </summary>
        internal static string SortedDesc {
            get {
                return ResourceManager.GetString("SortedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ungroup.
        /// </summary>
        internal static string UnGroup {
            get {
                return ResourceManager.GetString("UnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
