//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erestauracja.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordAndAnswer", Namespace="http://schemas.datacontract.org/2004/07/Contract")]
    [System.SerializableAttribute()]
    public partial class PasswordAndAnswer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLockedOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordAnswerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLockedOut {
            get {
                return this.IsLockedOutField;
            }
            set {
                if ((this.IsLockedOutField.Equals(value) != true)) {
                    this.IsLockedOutField = value;
                    this.RaisePropertyChanged("IsLockedOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordAnswer {
            get {
                return this.PasswordAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordAnswerField, value) != true)) {
                    this.PasswordAnswerField = value;
                    this.RaisePropertyChanged("PasswordAnswer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordAnswer", Namespace="http://schemas.datacontract.org/2004/07/Contract")]
    [System.SerializableAttribute()]
    public partial class PasswordAnswer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLockedOutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLockedOut {
            get {
                return this.IsLockedOutField;
            }
            set {
                if ((this.IsLockedOutField.Equals(value) != true)) {
                    this.IsLockedOutField = value;
                    this.RaisePropertyChanged("IsLockedOut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordQuestion", Namespace="http://schemas.datacontract.org/2004/07/Contract")]
    [System.SerializableAttribute()]
    public partial class PasswordQuestion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLockedOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLockedOut {
            get {
                return this.IsLockedOutField;
            }
            set {
                if ((this.IsLockedOutField.Equals(value) != true)) {
                    this.IsLockedOutField = value;
                    this.RaisePropertyChanged("IsLockedOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IEresService")]
    public interface IEresService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/ChangePassword", ReplyAction="http://tempuri.org/IEresService/ChangePasswordResponse")]
        bool ChangePassword(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/ChangePasswordQuestionAndAnswer", ReplyAction="http://tempuri.org/IEresService/ChangePasswordQuestionAndAnswerResponse")]
        bool ChangePasswordQuestionAndAnswer(string login, string newPwdQuestion, string newPwdAnswer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/GetPassword", ReplyAction="http://tempuri.org/IEresService/GetPasswordResponse")]
        Erestauracja.ServiceReference.PasswordAndAnswer GetPassword(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/GetPasswordAnswer", ReplyAction="http://tempuri.org/IEresService/GetPasswordAnswerResponse")]
        Erestauracja.ServiceReference.PasswordAnswer GetPasswordAnswer(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/ResetPassword", ReplyAction="http://tempuri.org/IEresService/ResetPasswordResponse")]
        bool ResetPassword(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/GetUserQuestion", ReplyAction="http://tempuri.org/IEresService/GetUserQuestionResponse")]
        Erestauracja.ServiceReference.PasswordQuestion GetUserQuestion(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/CreateUser", ReplyAction="http://tempuri.org/IEresService/CreateUserResponse")]
        bool CreateUser(string login, string password, string email, string name, string surname, string address, string townID, string country, System.DateTime birthdate, string sex, string telephone, string passwordQuestion, string passwordAnswer, bool isApproved);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/DeleteUser", ReplyAction="http://tempuri.org/IEresService/DeleteUserResponse")]
        bool DeleteUser(string login, bool deleteAllRelatedData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEresServiceChannel : Erestauracja.ServiceReference.IEresService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EresServiceClient : System.ServiceModel.ClientBase<Erestauracja.ServiceReference.IEresService>, Erestauracja.ServiceReference.IEresService {
        
        public EresServiceClient() {
        }
        
        public EresServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EresServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EresServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EresServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ChangePassword(string login, string password) {
            return base.Channel.ChangePassword(login, password);
        }
        
        public bool ChangePasswordQuestionAndAnswer(string login, string newPwdQuestion, string newPwdAnswer) {
            return base.Channel.ChangePasswordQuestionAndAnswer(login, newPwdQuestion, newPwdAnswer);
        }
        
        public Erestauracja.ServiceReference.PasswordAndAnswer GetPassword(string login) {
            return base.Channel.GetPassword(login);
        }
        
        public Erestauracja.ServiceReference.PasswordAnswer GetPasswordAnswer(string login) {
            return base.Channel.GetPasswordAnswer(login);
        }
        
        public bool ResetPassword(string login, string password) {
            return base.Channel.ResetPassword(login, password);
        }
        
        public Erestauracja.ServiceReference.PasswordQuestion GetUserQuestion(string login) {
            return base.Channel.GetUserQuestion(login);
        }
        
        public bool CreateUser(string login, string password, string email, string name, string surname, string address, string townID, string country, System.DateTime birthdate, string sex, string telephone, string passwordQuestion, string passwordAnswer, bool isApproved) {
            return base.Channel.CreateUser(login, password, email, name, surname, address, townID, country, birthdate, sex, telephone, passwordQuestion, passwordAnswer, isApproved);
        }
        
        public bool DeleteUser(string login, bool deleteAllRelatedData) {
            return base.Channel.DeleteUser(login, deleteAllRelatedData);
        }
    }
}
