//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erestauracja.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordAndAnswer", Namespace="http://schemas.datacontract.org/2004/07/Contract")]
    [System.SerializableAttribute()]
    public partial class PasswordAndAnswer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLockedOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordAnswerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLockedOut {
            get {
                return this.IsLockedOutField;
            }
            set {
                if ((this.IsLockedOutField.Equals(value) != true)) {
                    this.IsLockedOutField = value;
                    this.RaisePropertyChanged("IsLockedOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordAnswer {
            get {
                return this.PasswordAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordAnswerField, value) != true)) {
                    this.PasswordAnswerField = value;
                    this.RaisePropertyChanged("PasswordAnswer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordAnswer", Namespace="http://schemas.datacontract.org/2004/07/Contract")]
    [System.SerializableAttribute()]
    public partial class PasswordAnswer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLockedOutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLockedOut {
            get {
                return this.IsLockedOutField;
            }
            set {
                if ((this.IsLockedOutField.Equals(value) != true)) {
                    this.IsLockedOutField = value;
                    this.RaisePropertyChanged("IsLockedOut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordQuestion", Namespace="http://schemas.datacontract.org/2004/07/Contract")]
    [System.SerializableAttribute()]
    public partial class PasswordQuestion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLockedOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLockedOut {
            get {
                return this.IsLockedOutField;
            }
            set {
                if ((this.IsLockedOutField.Equals(value) != true)) {
                    this.IsLockedOutField = value;
                    this.RaisePropertyChanged("IsLockedOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Contract")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLockedOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastActivityDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastLockedOutDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastLoginDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastPasswordChangedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthdate {
            get {
                return this.BirthdateField;
            }
            set {
                if ((this.BirthdateField.Equals(value) != true)) {
                    this.BirthdateField = value;
                    this.RaisePropertyChanged("Birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApproved {
            get {
                return this.IsApprovedField;
            }
            set {
                if ((this.IsApprovedField.Equals(value) != true)) {
                    this.IsApprovedField = value;
                    this.RaisePropertyChanged("IsApproved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLockedOut {
            get {
                return this.IsLockedOutField;
            }
            set {
                if ((this.IsLockedOutField.Equals(value) != true)) {
                    this.IsLockedOutField = value;
                    this.RaisePropertyChanged("IsLockedOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastActivityDate {
            get {
                return this.LastActivityDateField;
            }
            set {
                if ((this.LastActivityDateField.Equals(value) != true)) {
                    this.LastActivityDateField = value;
                    this.RaisePropertyChanged("LastActivityDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastLockedOutDate {
            get {
                return this.LastLockedOutDateField;
            }
            set {
                if ((this.LastLockedOutDateField.Equals(value) != true)) {
                    this.LastLockedOutDateField = value;
                    this.RaisePropertyChanged("LastLockedOutDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastLoginDate {
            get {
                return this.LastLoginDateField;
            }
            set {
                if ((this.LastLoginDateField.Equals(value) != true)) {
                    this.LastLoginDateField = value;
                    this.RaisePropertyChanged("LastLoginDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastPasswordChangedDate {
            get {
                return this.LastPasswordChangedDateField;
            }
            set {
                if ((this.LastPasswordChangedDateField.Equals(value) != true)) {
                    this.LastPasswordChangedDateField = value;
                    this.RaisePropertyChanged("LastPasswordChangedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordQuestion {
            get {
                return this.PasswordQuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordQuestionField, value) != true)) {
                    this.PasswordQuestionField = value;
                    this.RaisePropertyChanged("PasswordQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TownID {
            get {
                return this.TownIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TownIDField, value) != true)) {
                    this.TownIDField = value;
                    this.RaisePropertyChanged("TownID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IEresService")]
    public interface IEresService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/ChangePassword", ReplyAction="http://tempuri.org/IEresService/ChangePasswordResponse")]
        bool ChangePassword(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/ChangePasswordQuestionAndAnswer", ReplyAction="http://tempuri.org/IEresService/ChangePasswordQuestionAndAnswerResponse")]
        bool ChangePasswordQuestionAndAnswer(string login, string newPwdQuestion, string newPwdAnswer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/GetPassword", ReplyAction="http://tempuri.org/IEresService/GetPasswordResponse")]
        Erestauracja.ServiceReference.PasswordAndAnswer GetPassword(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/GetPasswordAnswer", ReplyAction="http://tempuri.org/IEresService/GetPasswordAnswerResponse")]
        Erestauracja.ServiceReference.PasswordAnswer GetPasswordAnswer(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/ResetPassword", ReplyAction="http://tempuri.org/IEresService/ResetPasswordResponse")]
        bool ResetPassword(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/GetUserQuestion", ReplyAction="http://tempuri.org/IEresService/GetUserQuestionResponse")]
        Erestauracja.ServiceReference.PasswordQuestion GetUserQuestion(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/CreateUser", ReplyAction="http://tempuri.org/IEresService/CreateUserResponse")]
        bool CreateUser(string login, string password, string email, string name, string surname, string address, string townID, string country, System.DateTime birthdate, string sex, string telephone, string passwordQuestion, string passwordAnswer, bool isApproved);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/DeleteUser", ReplyAction="http://tempuri.org/IEresService/DeleteUserResponse")]
        bool DeleteUser(string login, bool deleteAllRelatedData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/GetAllUsers", ReplyAction="http://tempuri.org/IEresService/GetAllUsersResponse")]
        Erestauracja.ServiceReference.User[] GetAllUsers(out int totalRecords, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/GetNumberOfUsersOnline", ReplyAction="http://tempuri.org/IEresService/GetNumberOfUsersOnlineResponse")]
        int GetNumberOfUsersOnline(System.TimeSpan onlineSpan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/GetUser", ReplyAction="http://tempuri.org/IEresService/GetUserResponse")]
        Erestauracja.ServiceReference.User GetUser(string login, bool userIsOnline);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/GetUserById", ReplyAction="http://tempuri.org/IEresService/GetUserByIdResponse")]
        Erestauracja.ServiceReference.User GetUserById(int id, bool userIsOnline);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEresService/UnlockUser", ReplyAction="http://tempuri.org/IEresService/UnlockUserResponse")]
        bool UnlockUser(string login);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEresServiceChannel : Erestauracja.ServiceReference.IEresService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EresServiceClient : System.ServiceModel.ClientBase<Erestauracja.ServiceReference.IEresService>, Erestauracja.ServiceReference.IEresService {
        
        public EresServiceClient() {
        }
        
        public EresServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EresServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EresServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EresServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ChangePassword(string login, string password) {
            return base.Channel.ChangePassword(login, password);
        }
        
        public bool ChangePasswordQuestionAndAnswer(string login, string newPwdQuestion, string newPwdAnswer) {
            return base.Channel.ChangePasswordQuestionAndAnswer(login, newPwdQuestion, newPwdAnswer);
        }
        
        public Erestauracja.ServiceReference.PasswordAndAnswer GetPassword(string login) {
            return base.Channel.GetPassword(login);
        }
        
        public Erestauracja.ServiceReference.PasswordAnswer GetPasswordAnswer(string login) {
            return base.Channel.GetPasswordAnswer(login);
        }
        
        public bool ResetPassword(string login, string password) {
            return base.Channel.ResetPassword(login, password);
        }
        
        public Erestauracja.ServiceReference.PasswordQuestion GetUserQuestion(string login) {
            return base.Channel.GetUserQuestion(login);
        }
        
        public bool CreateUser(string login, string password, string email, string name, string surname, string address, string townID, string country, System.DateTime birthdate, string sex, string telephone, string passwordQuestion, string passwordAnswer, bool isApproved) {
            return base.Channel.CreateUser(login, password, email, name, surname, address, townID, country, birthdate, sex, telephone, passwordQuestion, passwordAnswer, isApproved);
        }
        
        public bool DeleteUser(string login, bool deleteAllRelatedData) {
            return base.Channel.DeleteUser(login, deleteAllRelatedData);
        }
        
        public Erestauracja.ServiceReference.User[] GetAllUsers(out int totalRecords, int pageIndex, int pageSize) {
            return base.Channel.GetAllUsers(out totalRecords, pageIndex, pageSize);
        }
        
        public int GetNumberOfUsersOnline(System.TimeSpan onlineSpan) {
            return base.Channel.GetNumberOfUsersOnline(onlineSpan);
        }
        
        public Erestauracja.ServiceReference.User GetUser(string login, bool userIsOnline) {
            return base.Channel.GetUser(login, userIsOnline);
        }
        
        public Erestauracja.ServiceReference.User GetUserById(int id, bool userIsOnline) {
            return base.Channel.GetUserById(id, userIsOnline);
        }
        
        public bool UnlockUser(string login) {
            return base.Channel.UnlockUser(login);
        }
    }
}
